version: 2.1

orbs:
  node: circleci/node@3.0.1

# Job defaults
defaults: &defaults
  working_directory: ~/project
  executor:
      name: node/default

# Filters for jobs that only need to be run for a version tag (release)
only-release: &only-release
  filters:
    # Ignore all branches
    branches:
      ignore: /.*/
    # And only run on version tags
    tags:
      only: /^v(\d+)\.(\d+)\.(\d+).*/

jobs:
  build:
    <<: *defaults
    steps:
      # Checkout the project
      - checkout

      # Restore NPM modules from cache
      - restore_cache:
          keys:
            - v1-root-{{ checksum "yarn.lock" }}
            - v1-root

      - run: 
          name: Install dependencies
          command: make install
      
      - run: 
          name: Build
          command: make

      - persist_to_workspace:
          root: ~/project
          paths:
            - dist

      # Restore NPM modules from cache
      - save_cache:
          key: v1-root-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  e2e-test:
    <<: *defaults
    steps:
      # Checkout the project
      - checkout

      # Get the build artifacts
      - attach_workspace:
          at: ~/project

      - restore_cache:
          keys:
            - v1-test-{{ checksum "test/yarn.lock" }}
            - v1-test
      
      - run: 
          name: Test package
          command: make test

      - save_cache:
          key: v1-test-{{ checksum "test/yarn.lock" }}
          paths:
            - test/node_modules

      - restore_cache:
          keys:
            - v1-examples-{{ checksum "examples/yarn.lock" }}
            - v1-examples

      - run: 
          name: Test examples
          command: make examples

      - save_cache:
          key: v1-examples-{{ checksum "examples/yarn.lock" }}
          paths:
            - examples/node_modules

  publish:
    <<: *defaults
    steps:
      # Checkout the project
      - checkout

      # Get the build artifacts
      - attach_workspace:
          at: ~/project
      
      - run:
          name: Authenticate for NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > dist/.npmrc

      - run:
          name: Publish package
          command: make publish

workflows:
  test:
    jobs:
      - build
      - e2e-test:
          requires:
              - build
  
  release:
    jobs:
      - build:
          <<: *only-release
      
      - e2e-test:
          <<: *only-release
          requires:
              - build

      - approve:
          <<: *only-release
          type: approval
          requires:
              - e2e-test

      - publish:
          <<: *only-release
          requires:
              - approve
